

name: Publish to Dockerhub ( image-uploader )

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'

jobs:
  update_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: beclab/images-uploader:${{ github.event.inputs.tags }}
        file: docker/uploader/Dockerfile
        platforms: linux/amd64, linux/arm64

